/*
 * COPYRIGHT (C) 2017
 * TOSHIBA ELECTRONIC DEVICES & STORAGE CORPORATION
 * ALL RIGHTS RESERVED
 *
 * THE SOURCE CODE AND ITS RELATED DOCUMENTATION IS PROVIDED "AS IS". TOSHIBA
 * ELECTRONIC DEVICES & STORAGE CORPORATION MAKES NO OTHER WARRANTY OF ANY
 * KIND, WHETHER EXPRESS, IMPLIED OR, STATUTORY AND DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, NON
 * INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
 *
 * THE SOURCE CODE AND DOCUMENTATION MAY INCLUDE ERRORS. TOSHIBA ELECTRONIC
 * DEVICES & STORAGE CORPORATION RESERVES THE RIGHT TO INCORPORATE
 * MODIFICATIONS TO THE SOURCE CODE IN LATER REVISIONS OF IT, AND TO MAKE
 * IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR THE PRODUCTS OR
 * TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME.
 *
 * TOSHIBA ELECTRONIC DEVICES & STORAGE CORPORATION SHALL NOT BE LIABLE FOR
 * ANY DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGE OR LIABILITY ARISING FROM YOUR
 * USE OF THE SOURCE CODE OR ANY DOCUMENTATION, INCLUDING BUT NOT LIMITED TO,
 * LOST REVENUES, DATA OR PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL OR
 * CONSEQUENTIAL NATURE, PUNITIVE DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS
 * ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, OR BEING UNUSABLE,
 * EVEN IF ADVISED OF THE POSSIBILITY OR PROBABILITY OF SUCH DAMAGES AND
 * WHETHER A CLAIM FOR SUCH DAMAGE IS BASED UPON WARRANTY, CONTRACT, TORT,
 * NEGLIGENCE OR OTHERWISE.
 */
/* VERSION : 20180905A */

#ifndef TCU_DEFS_H
#define TCU_DEFS_H

/*=== Service ===*/
/* Service ID  Definition */
#define TCU_FAT_SERVICE_ID_LE_MNG                                   (0xD1)
#define TCU_FAT_SERVICE_ID_LE_GATT_CLI                              (0xD2)
#define TCU_FAT_SERVICE_ID_LE_GATT_SER                              (0xD3)
#define TCU_FAT_SERVICE_ID_LE_SMP_MST                               (0xD4)
#define TCU_FAT_SERVICE_ID_LE_SMP_SLV                               (0xD5)
#define TCU_FAT_SERVICE_ID_LE_VEN                                   (0xEF)
#define TCU_FAT_SERVICE_ID_LE_VEN_ACCEPT                            (0xE1)

/*=== Opcode ===*/
/*-- ServiceID=0xD1 LE MNG Commands--*/
#define  TCU_LE_ACCEPT                                              (0xF1)
#define  TCU_LE_FATAL_ERROR                                         (0xFE)
#define  TCU_LE_SYS_INVALID_COMMAND                                 (0xFF)
#define  TCU_MNG_LE_INIT_REQ                                        (0x01)
#define  TCU_MNG_LE_INIT_RESP                                       (0x81)
#define  TCU_MNG_LE_SET_RAND_ADDRESS_REQ                            (0x04)
#define  TCU_MNG_LE_SET_RAND_ADDRESS_RESP                           (0x84)
#define  TCU_MNG_LE_READ_WHITELIST_SIZE_REQ                         (0x05)
#define  TCU_MNG_LE_READ_WHITELIST_SIZE_RESP                        (0x85)
#define  TCU_MNG_LE_ADD_DEVICE_TO_WHITELIST_REQ                     (0x06)
#define  TCU_MNG_LE_ADD_DEVICE_TO_WHITELIST_RESP                    (0x86)
#define  TCU_MNG_LE_DEL_WHITELIST_REQ                               (0x07)
#define  TCU_MNG_LE_DEL_WHITELIST_RESP                              (0x87)
#define  TCU_MNG_LE_START_ADVERTISE_REQ                             (0x08)
#define  TCU_MNG_LE_START_ADVERTISE_RESP                            (0x88)
#define  TCU_MNG_LE_DISABLE_ADVERTISE_REQ                           (0x09)
#define  TCU_MNG_LE_DISABLE_ADVERTISE_RESP                          (0x89)
#define  TCU_MNG_LE_SET_SCAN_ENABLE_REQ                             (0x0A)
#define  TCU_MNG_LE_SET_SCAN_ENABLE_RESP                            (0x8A)
#define  TCU_MNG_LE_SET_SCAN_DISABLE_REQ                            (0x0B)
#define  TCU_MNG_LE_SET_SCAN_DISABLE_RESP                           (0x8B)
#define  TCU_MNG_LE_CREATE_CONNECTION_REQ                           (0x0C)
#define  TCU_MNG_LE_CONNECTION_COMPLETE_EVENT                       (0x4C)
#define  TCU_MNG_LE_CREATE_CONNECTION_CANCEL_REQ                    (0x0D)
#define  TCU_MNG_LE_CREATE_CONNECTION_CANCEL_RESP                   (0x8D)
#define  TCU_MNG_LE_CONNECTION_UPDATE_REQ                           (0x0E)
#define  TCU_MNG_LE_UPDATE_CONN_REQ_EVENT                           (0x52)
#define  TCU_MNG_LE_CON_UPDATE_ACCEPT_REQ                           (0x16)
#define  TCU_MNG_LE_CON_UPDATE_ACCEPT_RESP                          (0x51)
#define  TCU_MNG_LE_L2CAP_CONNECTION_UPDATE_RESP                    (0x50)
#define  TCU_MNG_LE_L2CAP_CMD_REJECT_EVENT                          (0x53)
#define  TCU_MNG_LE_CONNECTION_UPDATE_EVENT                         (0x4E)
#define  TCU_MNG_LE_READ_REMOTE_USED_FEATURES_REQ                   (0x0F)
#define  TCU_MNG_LE_READ_REMOTE_USED_FEATURES_RESP                  (0x4F)
#define  TCU_MNG_LE_SET_HOST_CHANNEL_CLASSIFICATION_REQ             (0x10)
#define  TCU_MNG_LE_SET_HOST_CHANNEL_CLASSIFICATION_RESP            (0x90)
#define  TCU_MNG_LE_READ_CHANNEL_MAP_REQ                            (0x11)
#define  TCU_MNG_LE_READ_CHANNEL_MAP_RESP                           (0x91)
#define  TCU_MNG_LE_ADVERSTISE_REPORT_EVENT                         (0xC1)
#define  TCU_MNG_LE_DISCONNECT_REQ                                  (0x13)
#define  TCU_MNG_LE_DISCONNECT_EVENT                                (0x93)
#define  TCU_MNG_LE_READ_RSSI_REQ                                   (0x15)
#define  TCU_MNG_LE_READ_RSSI_RESP                                  (0x95)
#define  TCU_MNG_LE_GEN_RESOLVABLE_BDADDR_REQ                       (0x17)
#define  TCU_MNG_LE_GEN_RESOLVABLE_BDADDR_RESP                      (0x54)
#define  TCU_MNG_LE_RESOLVE_BDADDR_REQ                              (0x18)
#define  TCU_MNG_LE_RESOLVE_BDADDR_RESP                             (0x55)
#define  TCU_MNG_LE_READ_REMOTE_VERSION_REQ                         (0x19)
#define  TCU_MNG_LE_READ_REMOTE_VERSION_RESP                        (0x59)
#define  TCU_MNG_LE_SET_IR_VALUE_REQ                                (0x1B)
#define  TCU_MNG_LE_SET_IR_VALUE_RESP                               (0x5B)
#define  TCU_MNG_LE_ENCRYPT_REQ                                     (0x1C)
#define  TCU_MNG_LE_ENCRYPT_RESP                                    (0x5C)
#define  TCU_MNG_LE_SET_ADVERTISE_DATA_REQ                          (0x1D)
#define  TCU_MNG_LE_SET_ADVERTISE_DATA_RESP                         (0x5D)
#define  TCU_MNG_LE_REM_CON_PARAM_REQ_EVENT                         (0x5E)
#define  TCU_MNG_LE_REM_CON_PARAM_ACCEPT_REQ                        (0x1E)
#define  TCU_MNG_LE_REM_CON_PARAM_ACCEPT_RESP                       (0x9E)
#define  TCU_MNG_LE_WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT_REQ         (0x20)
#define  TCU_MNG_LE_WRITE_AUTHENTICATED_PAYLOAD_TIMEOUT_RESP        (0xA0)
#define  TCU_MNG_LE_AUTHENTICATED_PAYLOAD_TIMEOUT_EXPIRED_EVENT     (0x5F)
#define  TCU_MNG_LE_GEN_NON_RESOLVABLE_BDADDR_REQ                   (0x21)
#define  TCU_MNG_LE_GEN_NON_RESOLVABLE_BDADDR_RESP                  (0xA1)
#define  TCU_MNG_LE_GET_LE_STATUS_REQ                               (0x22)
#define  TCU_MNG_LE_GET_LE_STATUS_RESP                              (0xA2)
#define  TCU_MNG_LE_SET_DATA_LENGTH_REQ                             (0x26)
#define  TCU_MNG_LE_SET_DATA_LENGTH_RESP                            (0xA6)
#define  TCU_MNG_LE_DATA_LENGTH_CHANGE_EVENT                        (0x66)
#define  TCU_MNG_LE_WRITE_SUGG_DEFAULT_DATA_LEN_REQ                 (0x28)
#define  TCU_MNG_LE_WRITE_SUGG_DEFAULT_DATA_LEN_RESP                (0xA8)
#define  TCU_MNG_LE_ADD_DEVICE_FOR_LL_PRIVACY_REQ                   (0x2A)
#define  TCU_MNG_LE_ADD_DEVICE_FOR_LL_PRIVACY_RESP                  (0xAA)
#define  TCU_MNG_LE_REMOVE_DEVICE_FRM_LL_PRIVACY_REQ                (0x2B)
#define  TCU_MNG_LE_REMOVE_DEVICE_FRM_LL_PRIVACY_RESP               (0xAB)
#define  TCU_MNG_LE_CLEAR_ALL_DEVICES_FRM_LL_PRIVACY_REQ            (0x2C)
#define  TCU_MNG_LE_CLEAR_ALL_DEVICES_FRM_LL_PRIVACY_RESP           (0xAC)
#define  TCU_MNG_LE_READ_RESOLVING_LIST_SIZE_REQ                    (0x2D)
#define  TCU_MNG_LE_READ_RESOLVING_LIST_SIZE_RESP                   (0xAD)
#define  TCU_MNG_LE_READ_PEER_RESOLVABLE_ADDRESS_REQ                (0x2E)
#define  TCU_MNG_LE_READ_PEER_RESOLVABLE_ADDRESS_RESP               (0xAE)
#define  TCU_MNG_LE_READ_LOCAL_RESOLVABLE_ADDRESS_REQ               (0x2F)
#define  TCU_MNG_LE_READ_LOCAL_RESOLVABLE_ADDRESS_RESP              (0xAF)
#define  TCU_MNG_LE_ENABLE_LL_PRIVACY_REQ                           (0x3F)
#define  TCU_MNG_LE_ENABLE_LL_PRIVACY_RESP                          (0xBF)
#define  TCU_MNG_LE_DISABLE_LL_PRIVACY_REQ                          (0x40)
#define  TCU_MNG_LE_DISABLE_LL_PRIVACY_RESP                         (0xC0)
#define  TCU_MNG_LE_TRANSMITTER_TEST_REQ                            (0x42)
#define  TCU_MNG_LE_TRANSMITTER_TEST_RESP                           (0xC2)
#define  TCU_MNG_LE_RECEIVER_TEST_REQ                               (0x43)
#define  TCU_MNG_LE_RECEIVER_TEST_RESP                              (0xC3)
#define  TCU_MNG_LE_TEST_END_REQ                                    (0x44)
#define  TCU_MNG_LE_TEST_END_RESP                                   (0xC4)
#define  TCU_MNG_LE_RAND_COMMAND_REQ                                (0x45)
#define  TCU_MNG_LE_RAND_COMMAND_RESP                               (0xC5)
#define  TCU_MNG_LE_DIRECTED_ADV_REPORT_EVENT                       (0xD1)
#define  TCU_MNG_LE_GENERATE_P256_PUBLIC_KEY_REQ                    (0x46)
#define  TCU_MNG_LE_GENERATE_P256_PUBLIC_KEY_EVENT                  (0xC6)
#define  TCU_MNG_LE_GENERATE_DHKEY_REQ                              (0x47)
#define  TCU_MNG_LE_GENERATE_DHKEY_EVENT                            (0xC7)
#define  TCU_MNG_LE_READ_PHY_REQ                                    (0x38)
#define  TCU_MNG_LE_READ_PHY_RESP                                   (0xB8)
#define  TCU_MNG_LE_SET_DEFAULT_PHY_REQ                             (0x39)
#define  TCU_MNG_LE_SET_DEFAULT_PHY_RESP                            (0xB9)
#define  TCU_MNG_LE_SET_PHY_REQ                                     (0x3A)
#define  TCU_MNG_LE_PHY_UPDATE_COMPLETE_EVENT                       (0x7A)
#define  TCU_MNG_LE_ENHANCED_RECEIVER_TEST_REQ                      (0x61)
#define  TCU_MNG_LE_ENHANCED_RECEIVER_TEST_RESP                     (0xE1)
#define  TCU_MNG_LE_ENHANCED_TRANSMITTER_TEST_REQ                   (0x62)
#define  TCU_MNG_LE_ENHANCED_TRANSMITTER_TEST_RESP                  (0xE2)
#define  TCU_MNG_LE_SET_RAND_ADDRESS_FOR_EXT_ADV_SET_REQ            (0x65)
#define  TCU_MNG_LE_SET_RAND_ADDRESS_FOR_EXT_ADV_SET_RESP           (0xE5)
#define  TCU_MNG_LE_SET_EXT_ADV_PARAM_REQ                           (0x67)
#define  TCU_MNG_LE_SET_EXT_ADV_PARAM_RESP                          (0xE7)
#define  TCU_MNG_LE_SET_EXT_ADV_DATA_REQ                            (0x68)
#define  TCU_MNG_LE_SET_EXT_ADV_DATA_RESP                           (0xE8)
#define  TCU_MNG_LE_SET_EXT_SCAN_RSP_DATA_REQ                       (0x69)
#define  TCU_MNG_LE_SET_EXT_SCAN_RSP_DATA_RESP                      (0xE9)
#define  TCU_MNG_LE_SET_EXT_ADV_ENABLE_REQ                          (0x6A)
#define  TCU_MNG_LE_SET_EXT_ADV_ENABLE_RESP                         (0xEA)
#define  TCU_MNG_LE_ADV_SET_TERMINATED_EVENT                        (0x8C)
#define  TCU_MNG_LE_SET_EXT_ADV_DISABLE_REQ                         (0x6B)
#define  TCU_MNG_LE_SET_EXT_ADV_DISABLE_RESP                        (0xEB)
#define  TCU_MNG_LE_READ_MAX_ADV_DATA_LEN_REQ                       (0x6C)
#define  TCU_MNG_LE_READ_MAX_ADV_DATA_LEN_RESP                      (0xEC)
#define  TCU_MNG_LE_READ_NUM_SUPP_ADV_SETS_REQ                      (0x6D)
#define  TCU_MNG_LE_READ_NUM_SUPP_ADV_SETS_RESP                     (0xED)
#define  TCU_MNG_LE_DELETE_ADV_SET_REQ                              (0x6E)
#define  TCU_MNG_LE_DELETE_ADV_SET_RESP                             (0xEE)
#define  TCU_MNG_LE_SET_EXT_SCAN_ENABLE_REQ                         (0x63)
#define  TCU_MNG_LE_SET_EXT_SCAN_ENABLE_RESP                        (0xE3)
#define  TCU_MNG_LE_SET_EXT_SCAN_DISABLE_REQ                        (0x64)
#define  TCU_MNG_LE_SET_EXT_SCAN_DISABLE_RESP                       (0xE4)
#define  TCU_MNG_LE_EXTD_ADV_REPORT_EVENT                           (0xE6)
#define  TCU_MNG_LE_SCAN_TIMEOUT_EVENT                              (0x8E)
#define  TCU_MNG_LE_EXT_CREATE_CONN_REQ                             (0x3B)
#define  TCU_MNG_LE_READ_TRANSMIT_POWER_REQ                         (0x3C)
#define  TCU_MNG_LE_READ_TRANSMIT_POWER_RESP                        (0xBC)
#define  TCU_MNG_LE_READ_RF_PATH_COMPENSATION_REQ                   (0x3D)
#define  TCU_MNG_LE_READ_RF_PATH_COMPENSATION_RESP                  (0xBD)
#define  TCU_MNG_LE_WRITE_RF_PATH_COMPENSATION_REQ                  (0x3E)
#define  TCU_MNG_LE_WRITE_RF_PATH_COMPENSATION_RESP                 (0xBE)
#define  TCU_MNG_LE_SET_PRIVACY_MODE_REQ                            (0x48)
#define  TCU_MNG_LE_SET_PRIVACY_MODE_RESP                           (0xC8)
#define  TCU_MNG_LE_CHANNEL_SELECTION_ALGO_EVENT                    (0xBA)
#define  TCU_MNG_LE_SCAN_REQ_RCVD_EVENT                             (0xBB)
#define  TCU_MNG_LE_RD_ADV_CHNL_TX_POW_REQ                          (0x49)
#define  TCU_MNG_LE_RD_ADV_CHNL_TX_POW_RESP                         (0xC9)
#define  TCU_MNG_LE_CONFIG_CONN_COUNT_REQ                           (0x4A)
#define  TCU_MNG_LE_CONFIG_CONN_COUNT_RESP                          (0xCA)

/*-- ServiceID=0xD2 GATT Client Commands--*/
#define  TCU_LE_GATT_CLI_INIT_REQ                                   (0x00)
#define  TCU_LE_GATT_CLI_INIT_RESP                                  (0x80)
#define  TCU_LE_GATT_CLI_EXG_MTU_REQ                                (0x01)
#define  TCU_LE_GATT_CLI_EXG_MTU_EVENT                              (0x41)
#define  TCU_LE_GATT_CLI_DISCOVER_PRIM_SVC_REQ                      (0x02)
#define  TCU_LE_GATT_CLI_DISCOVER_PRIM_SVC_EVENT                    (0x42)
#define  TCU_LE_GATT_CLI_DISCOVER_PRIM_SVC_BY_UUID_REQ              (0x03)
#define  TCU_LE_GATT_CLI_DISCOVER_PRIM_SVC_BY_UUID_EVENT            (0x43)
#define  TCU_LE_GATT_CLI_FIND_INCL_SVC_REQ                          (0x04)
#define  TCU_LE_GATT_CLI_FIND_INCL_SVC_EVENT                        (0x44)
#define  TCU_LE_GATT_CLI_DISCOVER_CHAR_DECL_REQ                     (0x05)
#define  TCU_LE_GATT_CLI_DISCOVER_CHAR_DECL_EVENT                   (0x45)
#define  TCU_LE_GATT_CLI_DISCOVER_CHAR_DECL_BY_UUID_REQ             (0x06)
#define  TCU_LE_GATT_CLI_DISCOVER_CHAR_DECL_BY_UUID_EVENT           (0x46)
#define  TCU_LE_GATT_CLI_DISCOVER_CHAR_DESP_REQ                     (0x07)
#define  TCU_LE_GATT_CLI_DISCOVER_CHAR_DESP_EVENT                   (0x47)
#define  TCU_LE_GATT_CLI_READ_CHAR_VAL_REQ                          (0x08)
#define  TCU_LE_GATT_CLI_READ_CHAR_VAL_EVENT                        (0x48)
#define  TCU_LE_GATT_CLI_WRITE_CHAR_VAL_REQ                         (0x09)
#define  TCU_LE_GATT_CLI_WRITE_CHAR_VAL_EVENT                       (0x49)
#define  TCU_LE_GATT_CLI_READ_CHAR_DESP_REQ                         (0x0A)
#define  TCU_LE_GATT_CLI_READ_CHAR_DESP_EVENT                       (0x4A)
#define  TCU_LE_GATT_CLI_WRITE_CHAR_DESP_REQ                        (0x0B)
#define  TCU_LE_GATT_CLI_WRITE_CHAR_DESP_EVENT                      (0x4B)
#define  TCU_LE_GATT_CLI_READ_MULTIPLE_CHAR_VALUES_REQ              (0x0C)
#define  TCU_LE_GATT_CLI_READ_MULTIPLE_CHAR_VALUES_EVENT            (0x4C)
#define  TCU_LE_GATT_CLI_READ_CHAR_VAL_UUID_REQ                     (0x0D)
#define  TCU_LE_GATT_CLI_READ_CHAR_VAL_UUID_EVENT                   (0x4D)
#define  TCU_LE_GATT_CLI_RELIABLE_WRITES_REQ                        (0x0E)
#define  TCU_LE_GATT_CLI_RELIABLE_WRITES_EVENT                      (0x4E)
#define  TCU_LE_GATT_CLI_WRITE_WITHOUT_RESPONSE_CMD                 (0x0F)
#define  TCU_LE_GATT_CLI_WRITE_WITHOUT_RESPONSE_CMD_EVENT           (0x4F)
#define  TCU_LE_GATT_CLI_SIGNED_WRITE_WITHOUT_RESPONSE_CMD          (0x11)
#define  TCU_LE_GATT_CLI_SIGNED_WRITE_WITHOUT_RESPONSE_CMD_EVENT    (0x51)
#define  TCU_LE_GATT_CLI_READ_LONG_CHAR_VAL_REQ                     (0x12)
#define  TCU_LE_GATT_CLI_READ_LONG_CHAR_VAL_EVENT                   (0x52)
#define  TCU_LE_GATT_CLI_READ_LONG_CHAR_DESP_REQ                    (0x13)
#define  TCU_LE_GATT_CLI_READ_LONG_CHAR_DESP_EVENT                  (0x53)
#define  TCU_LE_GATT_CLI_WRITE_LONG_CHAR_VAL_REQ                    (0x14)
#define  TCU_LE_GATT_CLI_WRITE_LONG_CHAR_VAL_EVENT                  (0x54)
#define  TCU_LE_GATT_CLI_WRITE_LONG_CHAR_DESP_REQ                   (0x15)
#define  TCU_LE_GATT_CLI_WRITE_LONG_CHAR_DESP_EVENT                 (0x55)
#define  TCU_LE_GATT_CLI_CHAR_VAL_NOTIFICATION_IND_EVENT            (0xC0)
#define  TCU_LE_GATT_CLI_CHAR_VAL_INDICATION_IND_EVENT              (0xD0)
#define  TCU_LE_GATT_CLI_CHAR_VAL_CONFIRMATION_ACCEPT_REQ           (0x10)
#define  TCU_LE_GATT_CLI_CHAR_VAL_CONFIRMATION_ACCEPT_RESP          (0x90)

/*-- ServiceID=0xD3 GATT Server Commands--*/
#define  TCU_LE_GATT_SER_INIT_REQ                                   (0x00)
#define  TCU_LE_GATT_SER_INIT_RESP                                  (0x80)
#define  TCU_LE_GATT_SER_EXG_MTU_EVENT                              (0xC1)
#define  TCU_LE_GATT_SER_EXG_MTU_ACCEPT_REQ                         (0x01)
#define  TCU_LE_GATT_SER_EXG_MTU_ACCEPT_RESP                        (0x81)
#define  TCU_LE_GATT_SER_READ_CHAR_VAL_EVENT                        (0xC2)
#define  TCU_LE_GATT_SER_READ_CHAR_VAL_ACCEPT_REQ                   (0x02)
#define  TCU_LE_GATT_SER_READ_CHAR_VAL_ACCEPT_RESP                  (0x82)
#define  TCU_LE_GATT_SER_WRITE_CHAR_VAL_EVENT                       (0xC3)
#define  TCU_LE_GATT_SER_WRITE_CHAR_VAL_ACCEPT_REQ                  (0x03)
#define  TCU_LE_GATT_SER_WRITE_CHAR_VAL_ACCEPT_RESP                 (0x83)
#define  TCU_LE_GATT_SER_WRITE_CHAR_DESP_EVENT                      (0xC4)
#define  TCU_LE_GATT_SER_WRITE_CHAR_DESP_ACCEPT_REQ                 (0x04)
#define  TCU_LE_GATT_SER_WRITE_CHAR_DESP_ACCEPT_RESP                (0x84)
#define  TCU_LE_GATT_SER_SIGNED_WRITE_WITHOUT_RESPONSE_CMD_EVENT    (0xC5)
#define  TCU_LE_GATT_SER_CHAR_VAL_NOTIFICATION_REQ                  (0x05)
#define  TCU_LE_GATT_SER_CHAR_VAL_NOTIFICATION_EVENT                (0x45)
#define  TCU_LE_GATT_SER_CHAR_VAL_INDICATION_REQ                    (0x06)
#define  TCU_LE_GATT_SER_CHAR_VAL_INDICATION_EVENT                  (0x46)
#define  TCU_LE_GATT_SER_READ_CHAR_DESP_EVENT                       (0xC8)
#define  TCU_LE_GATT_SER_READ_CHAR_DESP_ACCEPT_REQ                  (0x08)
#define  TCU_LE_GATT_SER_READ_CHAR_DESP_ACCEPT_RESP                 (0x88)
#define  TCU_LE_GATT_SER_WRITE_WITHOUT_RESPONSE_CMD_EVENT           (0xC9)
#define  TCU_LE_GATT_SER_READ_MULTIPLE_EVENT                        (0xCA)
#define  TCU_LE_GATT_SER_READ_MULTIPLE_ACCEPT_REQ                   (0x0A)
#define  TCU_LE_GATT_SER_READ_MULTIPLE_ACCEPT_RESP                  (0x8A)
#define  TCU_LE_GATT_SER_PREP_WRITE_LONG_REL_CHAR_VAL_EVENT         (0xCB)
#define  TCU_LE_GATT_SER_PREP_WRITE_LONG_REL_CHAR_VAL_ACCEPT_REQ    (0x0B)
#define  TCU_LE_GATT_SER_PREP_WRITE_LONG_REL_CHAR_VAL_ACCEPT_RESP   (0x8B)
#define  TCU_LE_GATT_SER_PREP_WRITE_LONG_REL_CHAR_DESP_EVENT        (0xCC)
#define  TCU_LE_GATT_SER_PREP_WRITE_LONG_REL_CHAR_DESP_ACCEPT_REQ   (0x0C)
#define  TCU_LE_GATT_SER_PREP_WRITE_LONG_REL_CHAR_DESP_ACCEPT_RESP  (0x8C)
#define  TCU_LE_GATT_SER_READ_LONG_CHAR_VAL_EVENT                   (0xCD)
#define  TCU_LE_GATT_SER_READ_LONG_CHAR_VAL_ACCEPT_REQ              (0x0D)
#define  TCU_LE_GATT_SER_READ_LONG_CHAR_VAL_ACCEPT_RESP             (0x8D)
#define  TCU_LE_GATT_SER_READ_LONG_CHAR_DESP_EVENT                  (0xCE)
#define  TCU_LE_GATT_SER_READ_LONG_CHAR_DESP_ACCEPT_REQ             (0x0E)
#define  TCU_LE_GATT_SER_READ_LONG_CHAR_DESP_ACCEPT_RESP            (0x8E)
#define  TCU_LE_GATT_SER_EXECUTE_WRITE_CHAR_VAL_EVENT               (0xCF)
#define  TCU_LE_GATT_SER_EXECUTE_WRITE_CHAR_VAL_ACCEPT_REQ          (0x0F)
#define  TCU_LE_GATT_SER_EXECUTE_WRITE_CHAR_VAL_ACCEPT_RESP         (0x8F)
#define  TCU_LE_GATT_SER_EXECUTE_WRITE_CHAR_DESP_EVENT              (0xC7)
#define  TCU_LE_GATT_SER_EXECUTE_WRITE_CHAR_DESP_ACCEPT_REQ         (0x07)
#define  TCU_LE_GATT_SER_EXECUTE_WRITE_CHAR_DESP_ACCEPT_RESP        (0x87)
#define  TCU_LE_GATT_SER_EXECUTE_COMPLETE_EVENT                     (0x47)

/*-- ServiceID=0xD3 SDB Commands--*/
#define  TCU_LE_GATT_SDB_UPD_CHAR_ELE_REQ                           (0x25)
#define  TCU_LE_GATT_SDB_UPD_CHAR_ELE_RESP                          (0xA5)
#define  TCU_LE_GATT_SDB_RET_END_GRP_HLE_REQ                        (0x26)
#define  TCU_LE_GATT_SDB_RET_END_GRP_HLE_RESP                       (0xA6)
#define  TCU_LE_GATT_SDB_SET_ATTR_PERMS_REQ                         (0x29)
#define  TCU_LE_GATT_SDB_SET_ATTR_PERMS_RESP                        (0xA9)
#define  TCU_LE_GATT_SDB_GET_ATTR_PERMS_REQ                         (0x2A)
#define  TCU_LE_GATT_SDB_GET_ATTR_PERMS_RESP                        (0xAA)
#define  TCU_LE_GATT_SDB_GET_ATTR_TYPE_VALUE_REQ                    (0x2B)
#define  TCU_LE_GATT_SDB_GET_ATTR_TYPE_VALUE_RESP                   (0xAB)
#define  TCU_LE_GATT_SDB_UPD_OFFSET_CHAR_ELE_REQ                    (0x2D)
#define  TCU_LE_GATT_SDB_UPD_OFFSET_CHAR_ELE_RESP                   (0xAD)
#define  TCU_LE_GATT_SDB_ADD_ATTRIBUTE_REQ                          (0x27)
#define  TCU_LE_GATT_SDB_ADD_ATTRIBUTE_RESP                         (0xA7)
#define  TCU_LE_GATT_SDB_CLEAR_DATABASE_REQ                         (0x2E)
#define  TCU_LE_GATT_SDB_CLEAR_DATABASE_RESP                        (0xAE)
#define  TCU_LE_GATT_SDB_GET_DATABASE_INFO_REQ                      (0x2F)
#define  TCU_LE_GATT_SDB_GET_DATABASE_INFO_RESP                     (0xAF)

/*-- ServiceID=0xD4 SMP Master Commands--*/
#define  TCU_LE_SMP_MAS_PAIRING_REQ                                 (0x01)
#define  TCU_LE_SMP_MAS_PAIRING_EVENT                               (0x41)
#define  TCU_LE_SMP_MAS_SECURITY_EVENT                              (0xC2)
#define  TCU_LE_SMP_MAS_SECURITY_REJECT_REQ                         (0x02)
#define  TCU_LE_SMP_MAS_SECURITY_REJECT_RESP                        (0x82)
#define  TCU_LE_SMP_MAS_KEY_GEN_METHOD_EVENT                        (0xCB)
#define  TCU_LE_SMP_MAS_NUMERIC_COMPARISON_VERIFICATION_EVENT       (0x49)
#define  TCU_LE_SMP_MAS_NUMERIC_COMPARISON_CONFIRMATION_ACCEPT_REQ  (0x09)
#define  TCU_LE_SMP_MAS_NUMERIC_COMPARISON_CONFIRMATION_ACCEPT_RESP (0x89)
#define  TCU_LE_SMP_MAS_KEY_ENTRY_REQ_EVENT                         (0x44)
#define  TCU_LE_SMP_MAS_KEY_ENTRY_WRITE_REQ                         (0x05)
#define  TCU_LE_SMP_MAS_KEY_ENTRY_WRITE_RESP                        (0x85)
#define  TCU_LE_SMP_MAS_KEY_PRESS_NOTIFICATION_EVENT                (0x5A)
#define  TCU_LE_SMP_MAS_DISPLAY_KEY_EVENT                           (0x46)
#define  TCU_LE_SMP_MAS_DISPLAY_KEY_WRITE_REQ                       (0x07)
#define  TCU_LE_SMP_MAS_DISPLAY_KEY_WRITE_RESP                      (0x87)
#define  TCU_LE_SMP_MAS_STK_GENERATED_EVENT                         (0x48)
#define  TCU_LE_SMP_MAS_LTK_GENERATED_EVENT                         (0x4A)
#define  TCU_LE_SMP_MAS_LTK_RECEIVED_EVENT                          (0xC9)
#define  TCU_LE_SMP_MAS_EDIV_RAND_RECEIVED_EVENT                    (0xCA)
#define  TCU_LE_SMP_MAS_LTK_SENT_EVENT                              (0xCC)
#define  TCU_LE_SMP_MAS_EDIV_RAND_SENT_EVENT                        (0xCD)
#define  TCU_LE_SMP_MAS_IRK_RECEIVED_EVENT                          (0xD4)
#define  TCU_LE_SMP_MAS_IDENTITY_ADDRESS_RECEIVED_EVENT             (0xD5)
#define  TCU_LE_SMP_MAS_IRK_SENT_EVENT                              (0xD1)
#define  TCU_LE_SMP_MAS_IDENTITY_ADDRESS_SENT_EVENT                 (0xD2)
#define  TCU_LE_SMP_MAS_CSRK_RECEIVED_EVENT                         (0xD6)
#define  TCU_LE_SMP_MAS_CSRK_SENT_EVENT                             (0xD3)
#define  TCU_LE_SMP_MAS_PAIRING_COMPLETED_EVENT                     (0xD0)
#define  TCU_LE_SMP_MAS_START_LTK_ENCRYPT_REQ                       (0x08)
#define  TCU_LE_SMP_MAS_ENCRYPTION_CHANGE_EVENT                     (0xCE)
#define  TCU_LE_SMP_MAS_ENCRYPTION_KEY_REFRESH_COMPLETE_EVENT       (0xCF)
#define  TCU_LE_SMP_MAS_PAIRING_FAILED_EVENT                        (0x43)
#define  TCU_LE_SMP_MAS_PAIRING_FAILED_REQ                          (0x11)
#define  TCU_LE_SMP_MAS_PAIRING_FAILED_RESP                         (0x51)
#define  TCU_LE_SMP_MAS_BONDING_ENABLED_EVENT                       (0xD7)
#define  TCU_LE_SMP_MAS_STORE_KEY_EVENT                             (0xD8)
#define  TCU_LE_SMP_MAS_KEY_REQ_EVENT                               (0xD9)
#define  TCU_LE_SMP_MAS_KEY_ACCEPT_REQ                              (0x1B)
#define  TCU_LE_SMP_MAS_KEY_ACCEPT_RESP                             (0x9B)
#define  TCU_LE_SMP_MAS_BONDING_ENABLED_INFO_REQ                    (0x1A)
#define  TCU_LE_SMP_MAS_BONDING_ENABLED_INFO_RESP                   (0x9A)

/*-- ServiceID=0xD5 SMP Slave Commands--*/
#define  TCU_LE_SMP_SLV_SECURITY_REQ                                (0x02)
#define  TCU_LE_SMP_SLV_PAIRING_EVENT                               (0xC1)
#define  TCU_LE_SMP_SLV_PAIRING_ACCEPT_REQ                          (0x01)
#define  TCU_LE_SMP_SLV_PAIRING_ACCEPT_RESP                         (0x81)
#define  TCU_LE_SMP_SLV_KEY_GEN_METHOD_EVENT                        (0xCB)
#define  TCU_LE_SMP_SLV_NUMERIC_COMPARISON_VERIFICATION_EVENT       (0x49)
#define  TCU_LE_SMP_SLV_NUMERIC_COMPARISON_CONFIRMATION_ACCEPT_REQ  (0x09)
#define  TCU_LE_SMP_SLV_NUMERIC_COMPARISON_CONFIRMATION_ACCEPT_RESP (0x89)
#define  TCU_LE_SMP_SLV_KEY_ENTRY_REQ_EVENT                         (0x44)
#define  TCU_LE_SMP_SLV_KEY_ENTRY_WRITE_REQ                         (0x05)
#define  TCU_LE_SMP_SLV_KEY_ENTRY_WRITE_RESP                        (0x85)
#define  TCU_LE_SMP_SLV_KEY_PRESS_NOTIFICATION_EVENT                (0x5A)
#define  TCU_LE_SMP_SLV_DISPLAY_KEY_EVENT                           (0x46)
#define  TCU_LE_SMP_SLV_DISPLAY_KEY_WRITE_REQ                       (0x07)
#define  TCU_LE_SMP_SLV_DISPLAY_KEY_WRITE_RESP                      (0x87)
#define  TCU_LE_SMP_SLV_STK_GENERATED_EVENT                         (0x48)
#define  TCU_LE_SMP_SLV_LTK_GENERATED_EVENT                         (0x4A)
#define  TCU_LE_SMP_SLV_LTK_RECEIVED_EVENT                          (0xC9)
#define  TCU_LE_SMP_SLV_EDIV_RAND_RECEIVED_EVENT                    (0xCA)
#define  TCU_LE_SMP_SLV_LTK_SENT_EVENT                              (0xCC)
#define  TCU_LE_SMP_SLV_EDIV_RAND_SENT_EVENT                        (0xCD)
#define  TCU_LE_SMP_SLV_IRK_RECEIVED_EVENT                          (0xD6)
#define  TCU_LE_SMP_SLV_IDENTITY_ADDRESS_RECEIVED_EVENT             (0xD7)
#define  TCU_LE_SMP_SLV_IRK_SENT_EVENT                              (0xD3)
#define  TCU_LE_SMP_SLV_IDENTITY_ADDRESS_SENT_EVENT                 (0xD4)
#define  TCU_LE_SMP_SLV_CSRK_RECEIVED_EVENT                         (0xD8)
#define  TCU_LE_SMP_SLV_CSRK_SENT_EVENT                             (0xD5)
#define  TCU_LE_SMP_SLV_PAIRING_COMPLETED_EVENT                     (0xD2)
#define  TCU_LE_SMP_SLV_STK_ENCRYPT_SESSION_REQ_REPLY_EVENT         (0xCE)
#define  TCU_LE_SMP_SLV_LTK_ENCRYPT_SESSION_REQ_REPLY_EVENT         (0xCF)
#define  TCU_LE_SMP_SLV_ENCRYPTION_CHANGE_EVENT                     (0xD0)
#define  TCU_LE_SMP_SLV_ENCRYPTION_KEY_REFRESH_COMPLETE_EVENT       (0xD1)
#define  TCU_LE_SMP_SLV_PAIRING_FAILED_EVENT                        (0x43)
#define  TCU_LE_SMP_SLV_PAIRING_FAILED_REQ                          (0x13)
#define  TCU_LE_SMP_SLV_PAIRING_FAILED_RESP                         (0x53)
#define  TCU_LE_SMP_SLV_STORE_KEY_EVENT                             (0xD9)
#define  TCU_LE_SMP_SLV_KEY_REQ_EVENT                               (0xDA)
#define  TCU_LE_SMP_SLV_KEY_ACCEPT_REQ                              (0x1C)
#define  TCU_LE_SMP_SLV_KEY_ACCEPT_RESP                             (0x9C)
#define  TCU_LE_SMP_SLV_BONDING_ENABLED_INFO_REQ                    (0x1B)
#define  TCU_LE_SMP_SLV_BONDING_ENABLED_INFO_RESP                   (0x9B)

/*-- ServiceID=0xEF VEN Commands--*/
#define  TCU_VEN_SET_MODULE_MAINTENANCE_REQ                         (0x01)
#define  TCU_VEN_SET_MODULE_MAINTENANCE_EVENT                       (0x41)
#define  TCU_VEN_GET_MODULE_MAINTENANCE_REQ                         (0x02)
#define  TCU_VEN_GET_MODULE_MAINTENANCE_EVENT                       (0x42)
#define  TCU_VEN_MODULE_MAINTENANCE_INDICATOR_EVENT                 (0x43)

/*-- ServiceID=0xE1 VEN Command Accept--*/
#define  TCU_ACCEPT                                                 (0xF1)

/*=== Error Codes ===*/

/*-- LE MNG Error Codes (The below are HCI Error Codes returned by Controller ) --*/
#define TCU_LE_MNG_SUCCESS                                          (0x00)
#define TCU_LE_MNG_UNKNOWN_HCI_COMMAND                              (0x01)
#define TCU_LE_MNG_UNKNOWN_CONNECTION_IDENTIFIER                    (0x02)
#define TCU_LE_MNG_HARDWARE_FAILURE                                 (0x03)
#define TCU_LE_MNG_PAGE_TIMEOUT                                     (0x04)
#define TCU_LE_MNG_AUTHENTICATION_FAILURE                           (0x05)
#define TCU_LE_MNG_PIN_KEY_MISSING                                  (0x06)
#define TCU_LE_MNG_MEMORY_CAPACITY_EXCEEDED                         (0x07)
#define TCU_LE_MNG_CONNECTION_TIMEOUT                               (0x08)
#define TCU_LE_MNG_CONNECTION_LIMIT_EXCEEDED                        (0x09)
#define TCU_LE_MNG__SYNC_CONNECTION_LIMIT_EXCEEDED                  (0x0A)
#define TCU_LE_MNG_ACL_CONNECTION_ALREADY_EXISTS                    (0x0B)
#define TCU_LE_MNG_COMMAND_DISALLOWED                               (0x0C)
#define TCU_LE_MNG_CONNECTION_REJECTED_DUE_TO_LIMITED_RESOURCES     (0x0D)
#define TCU_LE_MNG_CONNECTION_REJECTED_DUE_TO_SECURITY_REASONS      (0x0E)
#define TCU_LE_MNG_CONNECTION_REJECTED_DUE_TO_UNACCEPTABLE_BD_ADDRESS (0x0F)
#define TCU_LE_MNG_CONNECTION_ACCEPT_TIMEOUR_EXCEEDED               (0x10)
#define TCU_LE_MNG_UNSUPPORTED_FEATURE                              (0x11)
#define TCU_LE_MNG_INVALID_HCI_PARAMETERS                           (0x12)
#define TCU_LE_MNG_CONNECTION_TERMINATED_BY_REMOTE_USER             (0x13)
#define TCU_LE_MNG_CONNECTION_TERMINATED_DUE_TO_LOW_RESOURCES       (0x14)
#define TCU_LE_MNG_CONNECTION_TERMINATED_DUE_TO_POWER_OFF           (0x15)
#define TCU_LE_MNG_CONNECTION_TERMINATED_BY_LOCAL_HOST              (0x16)
#define TCU_LE_MNG_REPEATED_ATTEMPTS                                (0x17)
#define TCU_LE_MNG_PAIRING_NOT_ALLOWED                              (0x18)
#define TCU_LE_MNG_UNKNOWN_LMP_PDU                                  (0x19)
#define TCU_LE_MNG_UNSUPPORTED_LMP_REMOTE_FEATURE                   (0x1A)
#define TCU_LE_MNG_SCO_OFFSET_REJECTED                              (0x1B)
#define TCU_LE_MNG_SCO_INTERVAL_REJECTED                            (0x1C)
#define TCU_LE_MNG_SCO_AIR_MODE_REJECTED                            (0x1D)
#define TCU_LE_MNG_INVALID_LMP_PARAMETERS                           (0x1E)
#define TCU_LE_MNG_UNSPECIFIED_ERROR                                (0x1F)
#define TCU_LE_MNG_UNSUPPORTED_LMP_PARAMETER_VALUE                  (0x20)
#define TCU_LE_MNG_ROLE_CHANGE_DISALLOWED                           (0x21)
#define TCU_LE_MNG_LL_RESPONSE_TIMEOUT                              (0x22)
#define TCU_LE_MNG_LMP_ERROR_TRANSACTION_COLLISION                  (0x23)
#define TCU_LE_MNG_LMP_PDU_NOT_ALLOWED                              (0x24)
#define TCU_LE_MNG_ENCRYPTION_MODE_NOT_ACCEPTABLE                   (0x25)
#define TCU_LE_MNG_LINK_KEY_CANNOT_BE_CHANGED                       (0x26)
#define TCU_LE_MNG_REQUESTED_QOS_NOT_SUPPORTED                      (0x27)
#define TCU_LE_MNG_INSTANT_PASSED                                   (0x28)
#define TCU_LE_MNG_PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED              (0x29)
#define TCU_LE_MNG_DIFFERENT_TRANSACTION_COLLISION                  (0x2A)
#define TCU_LE_MNG_RESERVED1                                        (0x2B)
#define TCU_LE_MNG_QOS_UNACCEPTABLE_PARAMETER                       (0x2C)
#define TCU_LE_MNG_QOS_REJECTED                                     (0x2D)
#define TCU_LE_MNG_CHANNEL_CLASSIFICATION_NOT_SUPPORTED             (0x2E)
#define TCU_LE_MNG_INSUFFICIENT_SECURITY                            (0x2F)
#define TCU_LE_MNG_PARAMETER_OUT_OF_MANDATORY_RANGE                 (0x30)
#define TCU_LE_MNG_RESERVED2                                        (0x31)
#define TCU_LE_MNG_ROLE_SWITCH_PENDING                              (0x32)
#define TCU_LE_MNG_RESERVED3                                        (0x33)
#define TCU_LE_MNG_RESERVED_SLOT_VIOLATION                          (0x34)
#define TCU_LE_MNG_ROLE_SWITCH_FAILED                               (0x35)
#define TCU_LE_MNG_EXTENDED_INQUIRY_RESPONSE_TOO_LARGE              (0x36)
#define TCU_LE_MNG_SECURE_SIMPLE_PAIRING_NOT_SUPPORTED_BY_HOST      (0x37)
#define TCU_LE_MNG_HOST_BUSY_PAIRING                                (0x38)
#define TCU_LE_MNG_CONNECTION_REJECTED_DUE_TO_NO_SUITABLE_CHANNEL_FOUND (0x39)
#define TCU_LE_MNG_CONTROLLER_BUSY                                  (0x3A)
#define TCU_LE_MNG_UNACCEPTABLE_CONNECTION_INTERVAL                 (0x3B)
#define TCU_LE_MNG_DIRECTED_ADVERTISING_TIMEOUT                     (0x3C)
#define TCU_LE_MNG_CONNECTION_TERMINATED_DUE_TO_MIC_FAILURE         (0x3D)
#define TCU_LE_MNG_CONNECTION_FAILED_TO_BE_ESTABLISHED              (0x3E)
#define TCU_LE_MNG_MAC_CONNECTION_FAILED                            (0x3F)

/*-- LE MNG Error Codes (GAP) --*/
#define TCU_LE_MNG_DEV_IS_NOT_INITED                                (0x81)
#define TCU_LE_MNG_COMMANDD_IN_PROGRESS                             (0x82)
#define TCU_LE_MNG_ECDH_KEY_GEN_ERROR                               (0x85)
#define TCU_LE_MNG_PARAMETER_ERROR                                  (0x86)
#define TCU_LE_MNG_OOB_DATA_GENERATION_ERROR                        (0x87)
#define TCU_LE_MNG_DEV_IS_ALREADY_INITIALIZED                       (0x89)
#define GAP_LE_SMP_ECDH_PROCEDURE_IN_PROGRESS                       (0x90)
#define GAP_LE_SMP_PUBLIC_KEY_NOT_GENERATED                         (0x91)
#define TCU_LE_MNG_DEV_ROLE_SLAVE                                   (0xA0)
#define TCU_LE_MNG_NO_ACL_LINK                                      (0xA1)
#define TCU_LE_MNG_DEVICE_ALREADY_CONNCETED                         (0xA2)
#define TCU_LE_MNG_MAX_DEVICES_ALREADY_CONNCETED                    (0xA3)
#define TCU_LE_MNG_ALREADY_ADVERTISING                              (0xA4)
#define TCU_LE_MNG_INVALID_CONNECTION_COUNT                         (0xA5)
#define TCU_LE_MNG_MAX_MASTER_CONNECTED                             (0xA6)
#define TCU_LE_MNG_MAX_SLAVE_CONNECTED                              (0xA7)
#define TCU_LE_MNG_PRIVACY_ENABLED_USE_RANDOM_ADDRESS               (0xA8)
#define TCU_LE_MNG_DEVICE_COMMAND_DISALLOWED                        (0x0C)

/*-- L2CAP Connection Oriented Error Codes --*/
#define TCU_LE_L2CAP_SUCCESS                                        (0x00)
#define TCU_LE_L2CAP_LE_PSM_ALREADY_REGISTERED                      (0x01)
#define TCU_LE_L2CAP_CONN_REFUSED_LE_PSM_NOT_SUPPORTED              (0x02)
#define TCU_LE_L2CAP_CONN_REFUSED_NO_RESOURCES_AVAILABLE            (0x04)
#define TCU_LE_L2CAP_CONN_REFUSED_INSUFFICIENT_AUTHENTICATION       (0x05)
#define TCU_LE_L2CAP_CONN_REFUSED_INSUFFICIENT_AUTHORIZATION        (0x06)
#define TCU_LE_L2CAP_CONN_REFUSED_INSUFFICIENT_ENCRYPTION_KEY_SIZE  (0x07)
#define TCU_LE_L2CAP_CONN_REFUSED_INSUFFICIENT_ENCRYPTION           (0x08)
#define TCU_LE_L2CAP_CONN_REFUSED_INVALID_SCID                      (0x09)
#define TCU_LE_L2CAP_CONN_REFUSED_SOURCE_CID_ALREADY_ALLOCATED      (0x0A)
#define TCU_LE_L2CAP_DEV_NOT_INITIALIZED                            (0x81)
#define TCU_LE_L2CAP_CMD_IN_PROGRESS                                (0x82)
#define TCU_LE_L2CAP_INVALID_PARAMETER_LENGTH                       (0x86)
#define TCU_LE_L2CAP_NO_ACL_LINK                                    (0xA1)
#define TCU_LE_L2CAP_LE_PSM_NOT_REGISTERED                          (0xA8)
#define TCU_LE_L2CAP_DATA_LENGTH_ERROR                              (0xA9)
#define TCU_LE_L2CAP_TIMEOUT                                        (0xAA)
#define TCU_LE_L2CAP_INVALID_CREDITS                                (0xAB)
#define TCU_LE_L2CAP_NOT_ENOUGH_CREDITS                             (0xAC)
#define TCU_LE_L2CAP_MAX_L2CAP_CONNECTON                            (0xAE)
#define TCU_LE_L2CAP_INVALID_RESPONSE                               (0xAF)
#define TCU_LE_L2CAP_BUFFER_FULL_ERROR                              (0xB3)

/*-- GATT Error Codes --*/
#define TCU_LE_GATT_SUCCESS                                         (0x00)
#define TCU_LE_GATT_LOOKUP_INVALID_HANDLE                           (0x01)
#define TCU_LE_GATT_READ_NOT_PERMITTED                              (0x02)
#define TCU_LE_GATT_WRITE_NOT_PERMITTED                             (0x03)
#define TCU_LE_GATT_INVALID_PDU                                     (0x04)
#define TCU_LE_GATT_INSUFFICIENT_AUTHENTICATION                     (0x05)
#define TCU_LE_GATT_REQ_NOT_SUPPORTED                               (0x06)
#define TCU_LE_GATT_INVALID_OFFSET                                  (0x07)
#define TCU_LE_GATT_INSUFFICIENT_AUTHORIZATION                      (0x08)
#define TCU_LE_GATT_PREPARE_QUEUE_FULL                              (0x09)
#define TCU_LE_GATT_LOOKUP_ATTRIBUTE_NOT_FOUND                      (0x0A)
#define TCU_LE_GATT_ATTRIBUTE_NOT_LONG                              (0x0B)
#define TCU_LE_GATT_INSUFFICIENT_ENCRYPTION_KEY_SIZE                (0x0C)
#define TCU_LE_GATT_INVALID_ATTRIBUTE_VALUE_LENGTH                  (0x0D)
#define TCU_LE_GATT_UNLIKELY_ERROR                                  (0x0E)
#define TCU_LE_GATT_INSUFFICIENT_ENCRYPTION                         (0x0F)
#define TCU_LE_GATT_LOOKUP_UNSUPPORTED_GRP_TYPE                     (0x10)
#define TCU_LE_GATT_INSUFFICIENT_RESOURCES                          (0x11)
#define TCU_LE_GATT_APPLICATION_ERROR                               (0xFE) 
#define TCU_LE_GATT_NOT_INITIALIZED                                 (0xA1)
#define TCU_LE_GATT_SMP_DATA_FAIL                                   (0xA2)
#define TCU_LE_GATT_INVALID_CONN_HANDLE                             (0xA3)
#define TCU_LE_GATT_DISCONNECT_ERROR                                (0xA4)
#define TCU_LE_GATT_REMOTE_PACKET_ERRONOUS_LENGTH                   (0xA5)
#define TCU_LE_GATT_INVALID_PARAM_LENGTH                            (0xA6)
#define TCU_LE_GATT_INVALID_REQUEST_OPCODE                          (0xA8)
#define TCU_LE_GATT_INITIALIZATION_ALREADY_DONE                     (0xA9)
#define TCU_LE_GATT_TIMEOUT_ERROR                                   (0xAA)
#define TCU_LE_GATT_INVALID_ACCEPT_REQ                              (0xAB)
#define TCU_LE_GATT_EXECUTE_WRITE_CANCEL                            (0xAC)
#define TCU_LE_GATT_BUFFER_FULL_ERROR                               (0xB3)

/*-- Error Codes generated in TCU_LE_ACCEPT response for GATT Requests --*/
#define TCU_LE_GATT_SUCCESS                                         (0x00)
#define TCU_LE_GATT_CLIENT_PARAM_ERROR                              (0x01)
#define TCU_LE_GATT_DEV_NOT_INITIALIZED                             (0x02)
#define TCU_LE_GATT_NO_ACL_LINK                                     (0x03)
#define TCU_LE_GATT_CLIENT_SECURITY_INFO_NULL                       (0x04)
#define TCU_LE_GATT_REQ_IN_PROGRESS                                 (0x10)
#define TCU_LE_GATT_CLIENT_LINK_NOT_AUTHENTICATED                   (0x11)
#define TCU_LE_GATT_CLIENT_LINK_IS_ENCRYTPED                        (0x12)
#define TCU_LE_GATT_SERVER_NOTIFICATION_NOT_ENABLED                 (0x13)
#define TCU_LE_GATT_SERVER_INDICATION_NOT_ENABLED                   (0x14)
#define TCU_LE_GATT_SERVER_MTU_REQ_IN_PROGRESS                      (0x15)
#define TCU_LE_GATT_INVALID_PACKET                                  (0xA6)
#define TCU_LE_GATT_BUFFER_FULL_ERROR                               (0xB3)

/*-- SDB Error Codes --*/
#define TCU_LE_SDB_SUCCESS                                          (0x00)
#define TCU_LE_SDB_LOOKUP_INVALID_HANDLE                            (0x01)
#define TCU_LE_SDB_GATT_NOT_INITIALIZED                             (0xA1)
#define TCU_LE_SDB_GATT_API_CONFLICT                                (0xA3)
#define TCU_LE_SDB_INVALID_PACKET                                   (0xA6)
#define TCU_LE_SDB_MEMORY_NOT_AVAILABLE                             (0xB0)
#define TCU_LE_SDB_MAX_CHAR_ELEMENTS_EXCEEDED                       (0xB1)
#define TCU_LE_SDB_BUFFER_FULL_ERROR                                (0xB3)

/*-- SMP Error Codes --*/
#define TCU_LE_SMP_SUCCESS                                          (0x00)
#define TCU_LE_SMP_PASS_KEY_ENTRY_FAILED                            (0x01)
#define TCU_LE_SMP_OOB_NOT_AVAILABLE                                (0x02)
#define TCU_LE_SMP_AUTH_REQUIREMENTS                                (0x03)
#define TCU_LE_SMP_CONFIRM_VALUE_FAILED                             (0x04)
#define TCU_LE_SMP_PAIRING_NOT_SUPPORTED                            (0x05)
#define TCU_LE_SMP_ENCRYPTION_KEY_SIZE                              (0x06)
#define TCU_LE_SMP_CMD_NOT_SUPPORTED                                (0x07)
#define TCU_LE_SMP_UNSPECIFIED_REASONS                              (0x08)
#define TCU_LE_SMP_REPEATED_ATTEMPTS                                (0x09)
#define TCU_LE_SMP_INVALID_PARAMETERS                               (0x0A)
#define TCU_LE_SMP_DHKEY_CHK_FAILED                                 (0x0B)
#define TCU_LE_SMP_NUMERIC_COMPARISON_FAILED                        (0x0C)
#define TCU_LE_SMP_DISCONNECT_ERROR                                 (0x84)
#define TCU_LE_SMP_PARAM_ERROR                                      (0x86)
#define TCU_LE_SMP_OOB_DATA_GENERATION_ERROR                        (0x87)
#define TCU_LE_SMP_DEV_ROLE_SLAVE                                   (0x90)
#define TCU_LE_SMP_DEV_ROLE_MASTER                                  (0x91)
#define TCU_LE_SMP_COMMAND_IN_PROGRESS                              (0x92)
#define TCU_LE_SMP_CSRK_NOT_AVAILABLE                               (0x93)
#define TCU_LE_SMP_DATA_SIGNING_ERROR                               (0x94)
#define TCU_LE_SMP_SIGNED_DATA_VERIFICATION_ERROR                   (0x95)
#define TCU_LE_SMP_NO_ACL_LINK                                      (0xA1)
#define TCU_LE_SMP_COMMAND_DISALLOWED                               (0xA2)
#define TCU_LE_SMP_TIME_OUT                                         (0xC0)
#define TCU_LE_SMP_DEVICE_ALREADY_TIMED_OUT                         (0xC1)
#define TCU_LE_SMP_NO_RESP_FROM_REMOTE                              (0xC2)
#define TCU_LE_SMP_NO_RESP_FROM_HOST                                (0xC3)
#define TCU_LE_SMP_REQUEST_REJECTED_BY_HOST                         (0xC4)
#define TCU_LE_SMP_2LL_IN_PROGRESS                                  (0xC5)
#define TCU_LE_SMP_DHKEY_GEN_FAILED                                 (0xC6)
#define TCU_LE_SMP_PUBLICKEY_GEN_FAILED                             (0xC7)
#define TCU_LE_SMP_LE_PUBLIC_KEY_NOT_GENERATED                      (0xC8)

#endif /* TCU_DEFS_H  */
